### ISSUE TITLE
Cron jobs

### ISSUE THREAD

**Issue by cdrx** [crisward/dokku-require#12]
Is there a feature to describe cron jobs in `app.json` with this plugin?

**Comment by crisward** [comment]
No... bit beyond scope I think. 

Nothing to stop someone also writing a plugin which also scans the app.json then sets up specific cron jobs, though I'm not sure that's the best place for them as app.json is not used when removing apps (as far as I know), so there is no way to remove those cron jobs. 

This is also true of databases, however cron jobs are a lot easier to miss. 

Perhaps have a go at writing a plugin. Feel free to clone this as a starting point. I didn't know bash scripting when I wrote this, so if I can do it....

**Comment by cdrx** [comment]
Understood :) thank you
