### ISSUE TITLE
Why not dokku core storage?

### ISSUE THREAD

**Issue by julienma** [crisward/dokku-require#3]
Hey, I'm very happy to see this plugin, I can finally get rid of most of my deployment scripts and really automate deployment of my DBs and volumes \o/

Quick question though: why [using docker volumes](https://github.com/crisward/dokku-require/blob/master/functions#L77) instead of [dokku core storage](http://dokku.viewdocs.io/dokku/dokku-storage/)? I'm genuinely interested, as I've started to switch to dokku storage for all my apps.

**Comment by crisward** [comment]
I needed to support an older dokku deploy < 5.
Thanks for the feedback. Perhaps if enough people like this I can convince dokku to add it into core.

**Comment by julienma** [comment]
And do you think it'd be possible to add support for core storage (it already work [out of the box on dokku > 0.5.0](http://dokku.viewdocs.io/dokku/dokku-storage/#usage))? :D

**Comment by crisward** [comment]
Looking at the dokku storage docs, it looks like it's just a wrapper around docker volumes. When you say add support, what did you have in mind?

**Comment by julienma** [comment]
Oh, I wasn't aware of that. I thought docker volumes and dokku storage were 2 different ways of managing persisting storage.
Well, if dokku storage is 100% compatible with docker volumes (which dokku-require uses), I don't have any more suggestion :)

**Comment by crisward** [comment]
thanks for the feedback. I'll close this issue. I'm pretty sure storage just creates the host directory as newer versions of docker don't do that automatically, which I'm pretty sure I included in require.
