### ISSUE TITLE
Permission issues with storage

### ISSUE THREAD

**Issue by kevinmickey** [crisward/dokku-require#5]
I included storage to mount in my app.json.  I tried to access that storage after using dokku enter $APP and appearing as herokuishuser, but I received a "Permission denied" error.

The permissions appear to be `-rw------- 1 32767 32767`.  The docs (https://github.com/dokku/dokku/blob/master/docs/advanced-usage/persistent-storage.md) recommend using chown `chown -R 32767:32767 /var/lib/dokku/data/storage/ruby-rails-sample`.  Can dokku-require check, and correct if necessary, the permissions of the storage it mounts.

(dokku/dokku#2215 seems relevant to this issue.)

**Comment by kevinmickey** [comment]
I think this issue arose from using scp to copy a file into the storage, so I'll close it, but I am interested in best practices.

**Comment by wooyek** [comment]
For anyone that get's here with a `-rw-------` permission problem for uploaded files in django, go see [FILE_UPLOAD_PERMISSIONS](https://docs.djangoproject.com/en/1.11/ref/settings/#file-upload-permissions) and set it to `0o644`
