### ISSUE TITLE
db is detected with app name but not being linked

### ISSUE THREAD

**Issue by kevinmickey** [crisward/dokku-require#6]
If you have a db (or other plugin) named appropriately with the app name, dokku-require declares it "already setup".  But the db may not be linked to your app.  So after checking for existence, it should check for linkage, and link if necessary.  (Thanks for a great plugin, by the way!)

**Comment by crisward** [comment]
Thanks for your feedback, and sorry for the slow reply...

This shouldn't be a difficult, at the moment it gives up if it can't create the database. I could make the link step separate which would fix this. It may however also try to link if it can't create the database for another reason. But it would fail, so no harm done.

**Comment by crisward** [comment]
That's been updated now. Hopefully it helps with your future deploys!
