### ISSUE TITLE
Does not work with Dockerfile deployments

### ISSUE THREAD

**Issue by Crote** [crisward/dokku-require#8]
I tried using this with a Dockerfile deployment, and nothing happened.
Is this supposed to work, or is it unsupported?

Here's what I did:
- Install docker and dokku
- Install the require plugin
- push an app with the following `app.json` in the root:

```json
{
  "dokku":{
    "plugins":[
      "postgres"
    ]
  }
}
```

After a successful app deployment, the postgres plugin was not installed and no database was created.

**Comment by Padrio** [comment]
Also not working with usual git deployment.

**Comment by crisward** [comment]
Which version of dokku are you using? This hasn't been touched much since dokku `0.4` but I've used it up to `0.12.7` without problem.

**Comment by crisward** [comment]
Also, to the original point, I don't use Dockerfile deployments so I've no idea. I imagine I may have to listen for different lifecycle events. It could be worth forking this and creating something specifically for that scenario.

**Comment by Padrio** [comment]
Im on Dokku 0.15.5 - i haven't checked whats the issue, yet. But if you need any further informations, just tell me.

**Comment by NiekKeijzer** [comment]
I ran into issues with this Dokku Require assuming Python2 is installed, while in fact it's not. I created pull request #11  to remedy this

**Comment by crisward** [comment]
Thanks for this, will merge in as soon as I've had chance to check.

**Comment by crisward** [comment]
Hoping this is fixed by the merge. Will close, feel free to update here if I'm incorrect.
Thanks all.
